[workspace]
members = ["avm_analyzer_app", "avm_analyzer_common", "avm_analyzer_server", "avm_stats"]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
